name: Validate CFG Files

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.cfg'
  push:
    branches: [ dev, main ]
    paths:
      - '**.cfg'

jobs:
  validate:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/validate.yml@0.0.4
